var images = ['file:///C:/users/paulp/desktop/fec-images/1.jpg', 
'file:///C:/users/paulp/desktop/fec-images/2.jpg',
'file:///C:/users/paulp/desktop/fec-images/3.jpg',
'file:///C:/users/paulp/desktop/fec-images/4.jpg',
'file:///C:/users/paulp/desktop/fec-images/5.jpg',
'file:///C:/users/paulp/desktop/fec-images/6.jpg',
'file:///C:/users/paulp/desktop/fec-images/7.jpg',
'file:///C:/users/paulp/desktop/fec-images/8.jpg',
'file:///C:/users/paulp/desktop/fec-images/9.jpg',
'file:///C:/users/paulp/desktop/fec-images/10.jpg',
'file:///C:/users/paulp/desktop/fec-images/11.jpg',
'file:///C:/users/paulp/desktop/fec-images/12.jpg',
'file:///C:/users/paulp/desktop/fec-images/13.jpg',
'file:///C:/users/paulp/desktop/fec-images/14.jpg',
'file:///C:/users/paulp/desktop/fec-images/15.jpg',
'file:///C:/users/paulp/desktop/fec-images/16.jpg',
'file:///C:/users/paulp/desktop/fec-images/17.jpg',
'file:///C:/users/paulp/desktop/fec-images/18.jpg',
'file:///C:/users/paulp/desktop/fec-images/19.jpg',
'file:///C:/users/paulp/desktop/fec-images/20.jpg',
'file:///C:/users/paulp/desktop/fec-images/21.jpg',
'file:///C:/users/paulp/desktop/fec-images/22.jpg',
'file:///C:/users/paulp/desktop/fec-images/23.jpg',
'file:///C:/users/paulp/desktop/fec-images/24.jpg',
'file:///C:/users/paulp/desktop/fec-images/25.jpg',
'file:///C:/users/paulp/desktop/fec-images/26.jpg',
'file:///C:/users/paulp/desktop/fec-images/27.jpg',
'file:///C:/users/paulp/desktop/fec-images/28.jpg',
'file:///C:/users/paulp/desktop/fec-images/29.jpg',
'file:///C:/users/paulp/desktop/fec-images/30.jpg',
'file:///C:/users/paulp/desktop/fec-images/31.jpg',
'file:///C:/users/paulp/desktop/fec-images/32.jpg',]

module.exports.images = images;